export const UsersArrayAluno = [
  {
    _id: 1,
    name: 'Ana Clara',
    email: 'ana.clara@example.com',
    password: 'senha123',
    Ra: "00002023001SP",
    curso: "Informática",
    turma: "1A",
    type: "Aluno",
    admin: false,
    createdAt: new Date('2023-01-01')
  },
  {
    _id: 2,
    name: 'Lucas Oliveira',
    email: 'lucas.oliveira@example.com',
    password: 'senha123',
    Ra: "00002023002SP",
    curso: null,
    turma: "2B",
    type: "Aluno",
    admin: true,
    createdAt: new Date('2023-01-02')
  },
  {
    _id: 3,
    name: 'Bruna Lima',
    email: 'bruna.lima@example.com',
    password: 'senha123',
    Ra: "00002023003SP",
    curso: "Administração",
    turma: "2B",
    type: "Aluno",
    admin: false,
    createdAt: new Date('2023-01-03')
  },
  {
    _id: 4,
    name: 'João Pedro',
    email: 'joao.pedro@example.com',
    password: 'senha123',
    Ra: "00002023004SP",
    curso: null,
    turma: "3A",
    type: "Aluno",
    admin: true,
    createdAt: new Date('2023-01-04')
  },
  {
    _id: 5,
    name: 'Fernanda Souza',
    email: 'fernanda.souza@example.com',
    password: 'senha123',
    Ra: "00002023005SP",
    curso: "Desenvolvimento de Sistemas",
    turma: "3C",
    type: "Aluno",
    admin: false,
    createdAt: new Date('2023-01-05')
  },
  {
    _id: 6,
    name: 'Rafael Silva',
    email: 'rafael.silva@example.com',
    password: 'senha123',
    Ra: "00002023006SP",
    curso: null,
    turma: "2A",
    type: "Aluno",
    admin: true,
    createdAt: new Date('2023-01-06')
  },
  {
    _id: 7,
    name: 'Camila Alves',
    email: 'camila.alves@example.com',
    password: 'senha123',
    Ra: "00002023007SP",
    curso: "Contabilidade",
    turma: "2A",
    type: "Aluno",
    admin: false,
    createdAt: new Date('2023-01-07')
  },
  {
    _id: 8,
    name: 'Diego Costa',
    email: 'diego.costa@example.com',
    password: 'senha123',
    Ra: "00002023008SP",
    curso: null,
    turma: "3B",
    type: "Aluno",
    admin: true,
    createdAt: new Date('2023-01-08')
  },
  {
    _id: 9,
    name: 'Mariana Rocha',
    email: 'mariana.rocha@example.com',
    password: 'senha123',
    Ra: "00002023009SP",
    curso: "Logística",
    turma: "1C",
    type: "Aluno",
    admin: false,
    createdAt: new Date('2023-01-09')
  },
  {
    _id: 10,
    name: 'Tiago Martins',
    email: 'tiago.martins@example.com',
    password: 'senha123',
    Ra: "00002023010SP",
    curso: null,
    turma: "3A",
    type: "Aluno",
    admin: true,
    createdAt: new Date('2023-01-10')
  },
  {
    _id: 11,
    name: 'Juliana Nunes',
    email: 'juliana.nunes@example.com',
    password: 'senha123',
    Ra: "00002023011SP",
    curso: "Enfermagem",
    turma: "3A",
    type: "Aluno",
    admin: false,
    createdAt: new Date('2023-01-11')
  },
  {
    _id: 12,
    name: 'Felipe Gomes',
    email: 'felipe.gomes@example.com',
    password: 'senha123',
    Ra: "00002023012SP",
    curso: null,
    turma: "2C",
    type: "Aluno",
    admin: true,
    createdAt: new Date('2023-01-12')
  },
  {
    _id: 13,
    name: 'Larissa Ribeiro',
    email: 'larissa.ribeiro@example.com',
    password: 'senha123',
    Ra: "00002023013SP",
    curso: "Marketing",
    turma: "1B",
    type: "Aluno",
    admin: false,
    createdAt: new Date('2023-01-13')
  },
  {
    _id: 14,
    name: 'Vinícius Moreira',
    email: 'vinicius.moreira@example.com',
    password: 'senha123',
    Ra: "00002023014SP",
    curso: null,
    turma: "3B",
    type: "Aluno",
    admin: true,
    createdAt: new Date('2023-01-14')
  },
  {
    _id: 15,
    name: 'Paula Mendes',
    email: 'paula.mendes@example.com',
    password: 'senha123',
    Ra: "00002023015SP",
    curso: "Redes de Computadores",
    turma: "2C",
    type: "Aluno",
    admin: false,
    createdAt: new Date('2023-01-15')
  },
  {
    _id: 16,
    name: 'Eduardo Lima',
    email: 'eduardo.lima@example.com',
    password: 'senha123',
    Ra: "00002023016SP",
    curso: null,
    turma: "1A",
    type: "Aluno",
    admin: true,
    createdAt: new Date('2023-01-16')
  },
  {
    _id: 17,
    name: 'Letícia Ferreira',
    email: 'leticia.ferreira@example.com',
    password: 'senha123',
    Ra: "00002023017SP",
    curso: "Informática",
    turma: "3B",
    type: "Aluno",
    admin: false,
    createdAt: new Date('2023-01-17')
  },
  {
    _id: 18,
    name: 'Bruno Castro',
    email: 'bruno.castro@example.com',
    password: 'senha123',
    Ra: "00002023018SP",
    curso: null,
    turma: "2B",
    type: "Aluno",
    admin: true,
    createdAt: new Date('2023-01-18')
  },
  {
    _id: 19,
    name: 'Sofia Martins',
    email: 'sofia.martins@example.com',
    password: 'senha123',
    Ra: "00002023019SP",
    curso: "Design Gráfico",
    turma: "1C",
    type: "Aluno",
    admin: false,
    createdAt: new Date('2023-01-19')
  },
  {
    _id: 20,
    name: 'Gustavo Andrade',
    email: 'gustavo.andrade@example.com',
    password: 'senha123',
    Ra: "00002023020SP",
    curso: null,
    turma: "3C",
    type: "Aluno",
    admin: true,
    createdAt: new Date('2023-01-20')
  },
];
