export const UsersArrayProfessor = [
  {
    _id: 1,
    name: 'Higona',
    email: 'john.doe@example.com',
    password: 'password123',
    Ra: "00003398867739SP",
    curso: "Desenvolvimento de Sistemas",
    turma: "3B",
    type: "Professor",
    admin: false,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2022-01-01'),
    isActive: true,
    isDeleted: false,
    isLocked: false,
    profilePicture: 'john_doe.jpg'
  },
  {
    _id: 2,
    name: 'Elu',
    email: 'jane.smith@example.com',
    password: 'password123',
    Rg: "00003398867740SP",
    type: "Professor",
    materia: "matemática",
    admin: true,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2022-01-01'),
    isActive: true,
    isDeleted: false,
    isLocked: false,
    profilePicture: 'jane_smith.jpg'
  },
];