export const UsersArrayProfessor = [
  {
    _id: 1,
    name: 'Carlos Silva',
    email: 'carlos.silva@example.com',
    password: 'password123',
    Rg: '12.345.678-9',  // RG gerado aleatoriamente
    type: "Professor",
    materia: "Matemática",
    admin: false,
    createdAt: new Date('2023-05-01'),
  },
  {
    _id: 2,
    name: 'Juliana Oliveira',
    email: 'juliana.oliveira@example.com',
    password: 'password123',
    Rg: '98.765.432-1',  // RG gerado aleatoriamente
    type: "Professor",
    materia: "Física",
    admin: true,
    createdAt: new Date('2023-06-15'),
  },
  {
    _id: 3,
    name: 'Rodrigo Souza',
    email: 'rodrigo.souza@example.com',
    password: 'password123',
    Rg: '23.456.789-0',  // RG gerado aleatoriamente
    type: "Professor",
    materia: "Química",
    admin: false,
    createdAt: new Date('2023-03-23'),
  },
  {
    _id: 4,
    name: 'Ana Lima',
    email: 'ana.lima@example.com',
    password: 'password123',
    Rg: '34.567.890-1',  // RG gerado aleatoriamente
    type: "Professor",
    materia: "Biologia",
    admin: true,
    createdAt: new Date('2023-04-10'),
  },
  {
    _id: 5,
    name: 'Pedro Costa',
    email: 'pedro.costa@example.com',
    password: 'password123',
    Rg: '56.789.012-3',  // RG gerado aleatoriamente
    type: "Professor",
    materia: "Geografia",
    admin: false,
    createdAt: new Date('2022-11-05'),
  },
  {
    _id: 6,
    name: 'Luciana Santos',
    email: 'luciana.santos@example.com',
    password: 'password123',
    Rg: '67.890.123-4',  // RG gerado aleatoriamente
    type: "Professor",
    materia: "História",
    admin: true,
    createdAt: new Date('2023-01-25'),
  },
  {
    _id: 7,
    name: 'Rafael Pereira',
    email: 'rafael.pereira@example.com',
    password: 'password123',
    Rg: '78.901.234-5',  // RG gerado aleatoriamente
    type: "Professor",
    materia: "Português",
    admin: false,
    createdAt: new Date('2022-08-19'),
  },
  {
    _id: 8,
    name: 'Mariana Gomes',
    email: 'mariana.gomes@example.com',
    password: 'password123',
    Rg: '89.012.345-6',  // RG gerado aleatoriamente
    type: "Professor",
    materia: "Artes",
    admin: true,
    createdAt: new Date('2023-02-02'),
  },
  {
    _id: 9,
    name: 'Lucas Alves',
    email: 'lucas.alves@example.com',
    password: 'password123',
    Rg: '90.123.456-7',  // RG gerado aleatoriamente
    type: "Professor",
    materia: "Educação Física",
    admin: false,
    createdAt: new Date('2023-07-10'),
  },
  {
    _id: 10,
    name: 'Isabela Martins',
    email: 'isabela.martins@example.com',
    password: 'password123',
    Rg: '01.234.567-8',  // RG gerado aleatoriamente
    type: "Professor",
    materia: "Inglês",
    admin: true,
    createdAt: new Date('2022-12-15'),
  },
  {
    _id: 11,
    name: 'Gustavo Rocha',
    email: 'gustavo.rocha@example.com',
    password: 'password123',
    Rg: '12.345.678-9',  // RG gerado aleatoriamente
    type: "Professor",
    materia: "Matemática",
    admin: false,
    createdAt: new Date('2023-04-18'),
  },
  {
    _id: 12,
    name: 'Paula Oliveira',
    email: 'paula.oliveira@example.com',
    password: 'password123',
    Rg: '23.456.789-0',  // RG gerado aleatoriamente
    type: "Professor",
    materia: "Física",
    admin: true,
    createdAt: new Date('2023-03-14'),
  },
  {
    _id: 13,
    name: 'João Santos',
    email: 'joao.santos@example.com',
    password: 'password123',
    Rg: '34.567.890-1',  // RG gerado aleatoriamente
    type: "Professor",
    materia: "Química",
    admin: false,
    createdAt: new Date('2023-05-20'),
  },
  {
    _id: 14,
    name: 'Marcio Pereira',
    email: 'marcio.pereira@example.com',
    password: 'password123',
    Rg: '45.678.901-2',  // RG gerado aleatoriamente
    type: "Professor",
    materia: "Geografia",
    admin: true,
    createdAt: new Date('2023-01-09'),
  },
  {
    _id: 15,
    name: 'Fernanda Costa',
    email: 'fernanda.costa@example.com',
    password: 'password123',
    Rg: '56.789.012-3',  // RG gerado aleatoriamente
    type: "Professor",
    materia: "História",
    admin: false,
    createdAt: new Date('2023-02-27'),
  },
  {
    _id: 16,
    name: 'Bruna Lima',
    email: 'bruna.lima@example.com',
    password: 'password123',
    Rg: '67.890.123-4',  // RG gerado aleatoriamente
    type: "Professor",
    materia: "Português",
    admin: true,
    createdAt: new Date('2022-10-12'),
  },
  {
    _id: 17,
    name: 'Felipe Gomes',
    email: 'felipe.gomes@example.com',
    password: 'password123',
    Rg: '78.901.234-5',  // RG gerado aleatoriamente
    type: "Professor",
    materia: "Artes",
    admin: false,
    createdAt: new Date('2023-06-03'),
  },
  {
    _id: 18,
    name: 'Natália Rocha',
    email: 'natalia.rocha@example.com',
    password: 'password123',
    Rg: '89.012.345-6',  // RG gerado aleatoriamente
    type: "Professor",
    materia: "Educação Física",
    admin: true,
    createdAt: new Date('2023-05-25'),
  },
  {
    _id: 19,
    name: 'Ricardo Martins',
    email: 'ricardo.martins@example.com',
    password: 'password123',
    Rg: '90.123.456-7',  // RG gerado aleatoriamente
    type: "Professor",
    materia: "Inglês",
    admin: false,
    createdAt: new Date('2023-07-02'),
  },
  {
    _id: 20,
    name: 'Eduardo Souza',
    email: 'eduardo.souza@example.com',
    password: 'password123',
    Rg: '01.234.567-8',  // RG gerado aleatoriamente
    type: "Professor",
    materia: "Matemática",
    admin: true,
    createdAt: new Date('2023-08-15'),
  }
];
