export const UsersArrayAluno = [
  {
    _id: 1,
    name: 'Ias',
    email: 'john.doe@example.com',
    password: 'password123',
    Ra: "00003398867739SP",
    curso: "Desenvolvimento de Sistemas",
    turma: "3B",
    type: "Aluno",
    admin: false,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2022-01-01'),
    isActive: true,
    isDeleted: false,
    isLocked: false,
    profilePicture: 'john_doe.jpg'
  },
  {
    _id: 2,
    name: 'Matt',
    email: 'jane.smith@example.com',
    password: 'password123',
    Ra: "00003398867740SP",
    type: "Aluno",
    admin: true,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2022-01-01'),
    isActive: true,
    isDeleted: false,
    isLocked: false,
    profilePicture: 'jane_smith.jpg'
  },
  {
    _id: 3,
    name: 'Ias',
    email: 'john.doe@example.com',
    password: 'password123',
    Ra: "00003398867739SP",
    curso: "Desenvolvimento de Sistemas",
    turma: "3B",
    type: "Aluno",
    admin: false,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2022-01-01'),
    isActive: true,
    isDeleted: false,
    isLocked: false,
    profilePicture: 'john_doe.jpg'
  },
  {
    _id: 4,
    name: 'Matt',
    email: 'jane.smith@example.com',
    password: 'password123',
    Ra: "00003398867740SP",
    type: "Aluno",
    admin: true,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2022-01-01'),
    isActive: true,
    isDeleted: false,
    isLocked: false,
    profilePicture: 'jane_smith.jpg'
  },
  {
    _id: 5,
    name: 'Ias',
    email: 'john.doe@example.com',
    password: 'password123',
    Ra: "00003398867739SP",
    curso: "Desenvolvimento de Sistemas",
    turma: "3B",
    type: "Aluno",
    admin: false,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2022-01-01'),
    isActive: true,
    isDeleted: false,
    isLocked: false,
    profilePicture: 'john_doe.jpg'
  },
  {
    _id: 6,
    name: 'Matt',
    email: 'jane.smith@example.com',
    password: 'password123',
    Ra: "00003398867740SP",
    type: "Aluno",
    admin: true,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2022-01-01'),
    isActive: true,
    isDeleted: false,
    isLocked: false,
    profilePicture: 'jane_smith.jpg'
  },
  {
    _id: 7,
    name: 'Ias',
    email: 'john.doe@example.com',
    password: 'password123',
    Ra: "00003398867739SP",
    curso: "Desenvolvimento de Sistemas",
    turma: "3B",
    type: "Aluno",
    admin: false,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2022-01-01'),
    isActive: true,
    isDeleted: false,
    isLocked: false,
    profilePicture: 'john_doe.jpg'
  },
  {
    _id: 8,
    name: 'Matt',
    email: 'jane.smith@example.com',
    password: 'password123',
    Ra: "00003398867740SP",
    type: "Aluno",
    admin: true,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2022-01-01'),
    isActive: true,
    isDeleted: false,
    isLocked: false,
    profilePicture: 'jane_smith.jpg'
  },
  {
    _id: 9,
    name: 'Ias',
    email: 'john.doe@example.com',
    password: 'password123',
    Ra: "00003398867739SP",
    curso: "Desenvolvimento de Sistemas",
    turma: "3B",
    type: "Aluno",
    admin: false,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2022-01-01'),
    isActive: true,
    isDeleted: false,
    isLocked: false,
    profilePicture: 'john_doe.jpg'
  },
  {
    _id: 10,
    name: 'Matt',
    email: 'jane.smith@example.com',
    password: 'password123',
    Ra: "00003398867740SP",
    type: "Aluno",
    admin: true,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2022-01-01'),
    isActive: true,
    isDeleted: false,
    isLocked: false,
    profilePicture: 'jane_smith.jpg'
  },
  {
    _id: 11,
    name: 'Ias',
    email: 'john.doe@example.com',
    password: 'password123',
    Ra: "00003398867739SP",
    curso: "Desenvolvimento de Sistemas",
    turma: "3B",
    type: "Aluno",
    admin: false,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2022-01-01'),
    isActive: true,
    isDeleted: false,
    isLocked: false,
    profilePicture: 'john_doe.jpg'
  },
  {
    _id: 12,
    name: 'Matt',
    email: 'jane.smith@example.com',
    password: 'password123',
    Ra: "00003398867740SP",
    type: "Aluno",
    admin: true,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2022-01-01'),
    isActive: true,
    isDeleted: false,
    isLocked: false,
    profilePicture: 'jane_smith.jpg'
  },
];